version: '3.8'

services:
  dockerproxy:
    image: wollomatic/socket-proxy:1.3.1 # see https://github.com/wollomatic/socket-proxy for reference
    deploy:
      replicas: 1
      resources:
        limits: 
          cpus: '1'
          memory: 64M
    healthcheck:
      test: [ 'CMD', '/healthcheck' ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - 2375:2375
    command:
      # with this configuration socket-proxy acts similar to the tecnativa proxy. For additional hardening
      # please refer to the documentation of the wollomatic/socket-proxy image
      - '-loglevel=debug' # set to debug for far more logging
      - '-allowfrom=10.0.0.0/16'
      - '-listenip=0.0.0.0'
      - '-allowGET=/v1\.45/(.+)' # this regexp allows readonly access to anything
      - '-shutdowngracetime=5'
      - '-watchdoginterval=600'
      - '-stoponwatchdog'
      - '-allowhealthcheck'
    user: 65534:1001 # replace <<docker-gid>> with the docker gid on your host system    
    read_only: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
